steps:
- name: 'gcr.io/cloud-builders/git'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      git init
      git remote add origin https://github.com/Metatavu/${REPO_NAME}.git
      git fetch --depth=1 origin $COMMIT_SHA
      git reset --hard FETCH_HEAD
      git submodule update --init
- name: gcr.io/cloud-builders/gcloud
  entrypoint: 'bash'
  args: 
  - '-c'
  - |
    if [ -n '${_DEPLOYMENT}' ]; then 
      mkdir ${_ENV}-data &&
      gcloud secrets versions access latest --secret=oioi-cm-api-${_ENV}-keycloak --format='get(payload.data)' | tr '_-' '/+' | base64 -d > ${_ENV}-data/keycloak.json
    fi
- name: maven:3.6.3-jdk-11
  entrypoint: 'bash'
  args: 
  - '-c'
  - mvn --no-transfer-progress -Drunmode=${_ENV} clean package
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args: 
  - '-c'
  - docker build -t ${_DOCKER_REPO_URL}:$(echo ${BUILD_ID} | cut -b 1-8) .
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  env:
    - "DEBIAN_FRONTEND=noninteractive"
    - "AWS_ACCESS_KEY_ID=${_AWS_ACCESS_KEY_ID}"
    - "AWS_SECRET_ACCESS_KEY=${_AWS_SECRET_ACCESS_KEY}"
    - "AWS_DEFAULT_REGION=${_AWS_DEFAULT_REGION}"
  args: 
  - '-c'
  - |
    if [ -n "${_DEPLOYMENT}" ]; then
      apt update && apt install -y unzip &&
      apt install -y wget build-essential
      curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip" &&
      unzip awscliv2.zip && ./aws/install &&
      aws ecr get-login-password | docker login --username AWS --password-stdin ${_DOCKER_REPO_URL}
      docker push ${_DOCKER_REPO_URL}:$(echo ${BUILD_ID} | cut -b 1-8)
    fi
- name: 'gcr.io/cloud-builders/kubectl'
  entrypoint: 'bash'
  env:
    - "AWS_ACCESS_KEY_ID=${_AWS_ACCESS_KEY_ID}"
    - "AWS_SECRET_ACCESS_KEY=${_AWS_SECRET_ACCESS_KEY}"
    - "AWS_DEFAULT_REGION=${_AWS_DEFAULT_REGION}"
  args:
  - '-c'
  - |
    if [ -n "${_DEPLOYMENT}" ]; then
      ./aws/install &&
      aws eks update-kubeconfig --name ${_CLUSTER} --region=${_AWS_DEFAULT_REGION} &&
      kubectl -n ${_NAMESPACE} set image deployment/${_DEPLOYMENT} ${_DEPLOYMENT}=${_DOCKER_REPO_URL}:$(echo ${BUILD_ID} | cut -b 1-8)
    fi
