version: "3"
services:
  mysql:
    image: mysql:5.6
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - 3306:3306
    command: --lower_case_table_names=1
    container_name: oioi-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: oioi
      MYSQL_USER: oioi
      MYSQL_PASSWORD: password

  keycloak:
    image: quay.io/keycloak/keycloak:13.0.1
    container_name: oioi-keycloak
    ports:
      - 8080:8080
    depends_on:
      - mysql
    environment:
      DB_VENDOR: mysql
      DB_DATABASE: keycloak
      DB_USER: root
      DB_ADDR: mysql
      DB_PASSWORD: root
      JDBC_PARAMS: useSSL=false&allowPublicKeyRetrieval=true

  oioi:
    build:
      context: .
      dockerfile: src/main/docker/Dockerfile.jvm
    ports:
      - 8081:8080
    container_name: oioi-api
    depends_on:
      - mysql
    env_file:
      .env

volumes:
  db_data: {}